### ISSUE TITLE
FEATURE: store configuration in DynamoDB table(s)

### ISSUE THREAD

**Issue by astrostl** [strofimovsky/aws-rolling-snaps#11]
The zip upload method has two files: the code, and a static config. Could the config be moved out to a tiny DynamoDB table? This would simplify deployments, permit live configuration edits, and pave the road for multiple configuration sets (e.g. MakeSnapshot=true or MakeSnapshot=altconfig).

**Comment by strofimovsky** [comment]
I believe #13 fixes this one as well
