### ISSUE TITLE
FEATURE: use Lamba env vars for configuration

### ISSUE THREAD

**Issue by astrostl** [strofimovsky/aws-rolling-snaps#13]
https://aws.amazon.com/blogs/aws/new-for-aws-lambda-environment-variables-and-serverless-application-model/

This would eliminate the need for a zip bundle, and permit live changes w/o uploading code w/o needing to majorly refactor over to something like DynamoDB

**Comment by strofimovsky** [comment]
Nice feature! Should probably update the CF template as well.
