### ISSUE TITLE
is it possible to run aws-rolling-snaps from instance without putting the keys on the instance?

### ISSUE THREAD

**Issue by dprob** [strofimovsky/aws-rolling-snaps#3]
I am trying to setup up the snapshot job without putting the credentials on the aws instance.  However, I received the following error:

No handlers could be found for logger "makesnap3"
Started taking days snapshots at 26-07-2016 19:23:21
Can't access volume list:<class 'botocore.exceptions.NoRegionError'>
You must specify a region.

Finished making snapshots at 26-07-2016 19:23:21 for 0 volume(s), 1 errors
Created: 0, deleted: 0, errors: 0

I then attempted to add 'ec2_region_name': 'xx-xxxx-1', to the config.json file

...and I received the same error.

When the original "evannuil/aws-snapshot-tool" was working I could use the following to snapshot instances and not store the keys on the instance...
## start virtual environment

. snapshotinstance/bin/activate

IFS='
'
CREDARRAY=($(aws sts assume-role --duration-seconds 3600 --role-arn "arn:aws:iam::acctXXXXX:role/snapshotme" --role-session-name "snapshot-script" |grep -w 'SecretAccessKey|SessionToken|AccessKeyId' |awk '{print $2}'  |sed 's/\"//g;s/\,//'``))
## put information into variables

export AWS_SECRET_ACCESS_KEY=${CREDARRAY[0]}
export AWS_SECURITY_TOKEN=${CREDARRAY[1]}
export AWS_ACCESS_KEY_ID=${CREDARRAY[2]}
## start the snapshot script

makesnap3.py day
## put information into variables

unset AWS_SECRET_ACCESS_KEY
unset AWS_SECURITY_TOKEN
unset AWS_ACCESS_KEY_ID

Any ideas?  Unfortunately we can't use Lambda as some of the instances are rather large.

**Comment by strofimovsky** [comment]
One of the perks of using boto3 is that you can assume roles with STS natively, without shell tricks. Try this method: http://boto3.readthedocs.io/en/latest/guide/configuration.html#assume-role-provider

**Comment by dprob** [comment]
Interesting; however, that appears I need to install the aws cli on the instance, correct?

**Comment by strofimovsky** [comment]
It doesn't seem that you need CLI for that, it's just boto3 use similar or the same configuration files as CLI.

**Comment by dprob** [comment]
Thanks Sergey. I am trying to run the script without having any key information in files on the instance (for security reasons). Initially I will run this script from an instance in one aws account. Eventually I will run this from an instance in one aws account, but list the other aws account numbers in a file, but no key information.

**Comment by dprob** [comment]
Perhaps this will help explain.  I added the following to the makesnap3.py.  The reason for doing this is to not have to write the keys to the instance, but it appears the script still wants the ./aws files:

## Create a session with the proper S3 permissions

client = boto3.client('sts')

## assume snapshot role

role = 'arn:aws:iam::xxxxxxxxxxxx:role/snapshot'

assumed_role = client.assume_role(RoleArn=role, RoleSessionName='snapshot-session')

## get session keys

sts = boto3.client('sts', aws_access_key_id=assumed_role['Credentials']['AccessKeyId'],
                          aws_secret_access_key=assumed_role['Credentials']['SecretAccessKey'],
                          aws_session_token=assumed_role['Credentials']['SessionToken'])

thoughts?

**Comment by strofimovsky** [comment]
OK, I think I see what you're trying to achieve here. You can set default region in AWS_DEFAULT_REGION environment variable as well.

Anyway, I try to keep compatibility with evannuil's version to a maximum - you can set the region in config file now. So the method you mentioned first would work too.
