### ISSUE TITLE
wish: use only the snapshot rotation feature, not snapshot creation

### ISSUE THREAD

**Issue by markstos** [strofimovsky/aws-rolling-snaps#6]
I want o create my snapshots from within each instance, so I that I have the flexibility to do things like freeze the filesystem or temporarily or lock a database before running the snapshot-- I use the `ec2-create-snapshot` tool.

I would like to delete/rotate my snapshots using Lamba and an event schedule, so it would it be great of there was an option in this tool to disable snapshot creation.

**Comment by strofimovsky** [comment]
Seems like a reasonable feature, here you are.
