### ISSUE TITLE
wish: unit tests for rotation calculations

### ISSUE THREAD

**Issue by markstos** [strofimovsky/aws-rolling-snaps#7]
Given that this project deletes data, it would be re-assuring if the algorithms for for deleting the daily/weekly/monthly snapshots had some unit tests to confirm they deleted the expected combinations in a variety of situations.

**Comment by strofimovsky** [comment]
Calculations for daily/weekly/monthly rotation use the same logic but work independently on a corresponding (daily/weekly/monthly) run. Though an extra test never hurt anyone, I put some usual scenarios to the test. If you can think of any other scenarios - feel free to add it, or suggest it to me. Thank you!
