### ISSUE TITLE
DOCS: explicit instance/volume tag explanation

### ISSUE THREAD

**Issue by astrostl** [strofimovsky/aws-rolling-snaps#9]
`"If you will only snapshot from volume tags, not instances, you can omit the "ec2:DescribeInstances" permission." -> "Don't forget to mark EBS volumes that you wish to snapshot with a tag ('MakeSnapshot': 'true' by default)"`

I didn't realize that the script will work on tagged volumes OR tagged instances (all of that instance's volumes). Could this be cleaned up in the docs a bit, if that is the intention? Also, what will the behavior be if both an instance and its volumes are tagged?

**Comment by strofimovsky** [comment]
I hope that explains it
